-- Run this in Supabase SQL Editor.
create table if not exists public.reviews (
  id bigint generated by default as identity primary key,
  name text not null check (char_length(name) between 1 and 40),
  rating integer not null check (rating between 1 and 5),
  text text not null check (char_length(text) between 1 and 500),
  created_at timestamptz not null default now()
);

alter table public.reviews enable row level security;

revoke all on table public.reviews from anon, authenticated;
grant select, insert on table public.reviews to anon;

create policy "Public can read customer reviews"
on public.reviews for select to anon using (true);

create policy "Public can submit customer reviews"
on public.reviews for insert to anon
with check (char_length(name) between 1 and 40 and rating between 1 and 5 and char_length(text) between 1 and 500);

-- For Supabase projects created under the 2026 Data API defaults, make sure
-- the reviews table is exposed to the Data API as well.


-- Global visitor counter (one row per browser/device ID).
create table if not exists public.site_visitors (
  visitor_id text primary key check (char_length(visitor_id) between 10 and 100),
  last_seen timestamptz not null default now()
);

alter table public.site_visitors enable row level security;
revoke all on table public.site_visitors from anon, authenticated;

create or replace function public.register_visit(p_visitor_id text)
returns bigint
language plpgsql
security definer
set search_path = public
as $$
begin
  if p_visitor_id is null or char_length(p_visitor_id) < 10 or char_length(p_visitor_id) > 100 then
    raise exception 'invalid visitor id';
  end if;
  insert into public.site_visitors(visitor_id,last_seen) values(p_visitor_id,now())
  on conflict (visitor_id) do update set last_seen=now();
  return (select count(*) from public.site_visitors);
end;
$$;

revoke all on function public.register_visit(text) from public, anon, authenticated;
grant execute on function public.register_visit(text) to anon;
